version: '3.8'
services:
  app:
    build: ./docker/php
    container_name: laravel_app_v2
    volumes:
      - ./laravel-app:/var/www
    depends_on:
      - mysql

  nginx:
    image: nginx:1.21.1
    container_name: nginx_v2
    ports:
      - "8000:80"
    volumes:
      - ./laravel-app:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8.0.26
    ports:
    - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: laravel_db
        MYSQL_USER: laravel_user
        MYSQL_PASSWORD: laravel_pass
    command:
        mysqld --default-authentication-plugin=mysql_native_password
    volumes:
        - ./docker/mysql/data:/var/lib/mysql
        - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysql
        - PMA_USER=laravel_user
        - PMA_PASSWORD=laravel_pass
    depends_on:
        - mysql
    ports:
        - 8080:80

  node:
    image: node:22.12.0
    container_name: react_vite
    working_dir: /app
    volumes:
      - ./react-app/app:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
